/**
 * Created by SNAKE on 2017/9/8.
 */
define([], function () {
    //搜索的 筛选条件
    var conditionMap = {
        pcCondition: [
            {
                name: "包邮",
                value: "baoyou",
                select: false
            }, {
                name: "退货运费险",
                value: "auction_tag[385]",
                select: false
            }, {
                name: "货到付款",
                value: "support_cod",
                select: false
            }, {
                name: "海外商品",
                value: "globalbuy",
                select: false
            }, {
                name: "二手",
                value: "filterFineness",
                select: false
            }, {
                name: "天猫",
                value: "filter_tianmao",
                select: false
            }, {
                name: "正品保障",
                value: "user_type",
                select: false
            }, {
                name: "7天退换货",
                value: "auction_tag[4806]",
                select: false
            }, {
                name: "新品",
                value: "auction_tag[1154]",
                select: false
            }
        ],
        pcTmallCondition: [
            {
                name: "包邮",
                value: "post_fee",
                select: false
            }, {
                name: "折扣",
                value: "miaosha",
                select: false
            }, {
                name: "搭配减价",
                value: "combo",
                select: false
            }, {
                name: "满就减",
                value: "filter_mj",
                select: false
            }, {
                name: "货到付款",
                value: "support_cod",
                select: false
            }, {
                name: "新到商品",
                value: "new",
                select: false
            }
        ],
        wxTmallCondition: [
            {
                name: "包邮",
                value: "post_fee",
                select: false
            },
            {
                name: "折扣",
                value: "miaosha",
                select: false
            }, {
                name: "搭配减价",
                value: "combo",
                select: false
            }, {
                name: "天猫国际",
                value: "auction_tag[71682]",
                select: false
            }
        ],
        wxCondition: [
            {
                name: "包邮",
                value: "myf",
                select: false
            },
            {
                name: "天猫",
                value: "mall",
                select: false
            }, {
                name: "全球购",
                value: "hwsp",
                select: false
            }, {
                name: "消费者保障",
                value: "xfzbz",
                select: false
            }, {
                name: "手机专享价",
                value: "service_sjzx",
                select: false
            }, {
                name: "淘金币抵钱",
                value: "tjb",
                select: false
            }, {
                name: "货到付款",
                value: "hdfk",
                select: false
            }, {
                name: "七天退货",
                value: "qtth",
                select: false
            }
        ]
    };
    //搜索 发货地
    var locsList = [
        {
            name: "北京",
            value: "北京"
        }, {
            name: "上海",
            value: "上海"
        }, {
            name: "广州",
            value: "广州"
        }, {
            name: "深圳",
            value: "深圳"
        }, {
            name: "杭州",
            value: "杭州"
        }, {
            name: "海外",
            value: "海外"
        }, {
            name: "江浙沪",
            value: "江浙沪"
        }, {
            name: "珠三角",
            value: "珠三角"
        }, {
            name: "京津冀",
            value: "京津冀"
        }, {
            name: "东三省",
            value: "东三省"
        }, {
            name: "港澳台",
            value: "港澳台"
        }, {
            name: "浙江沪皖",
            value: "浙江沪皖"
        }, {
            name: "长沙",
            value: "长沙"
        }, {
            name: "长春",
            value: "长春"
        }, {
            name: "成都",
            value: "成都"
        }, {
            name: "重庆",
            value: "重庆"
        }, {
            name: "大连",
            value: "大连"
        }, {
            name: "东莞",
            value: "东莞"
        }, {
            name: "佛山",
            value: "佛山"
        }, {
            name: "福州",
            value: "福州"
        }, {
            name: "贵阳",
            value: "贵阳"
        }, {
            name: "合肥",
            value: "合肥"
        }, {
            name: "金华",
            value: "金华"
        }, {
            name: "济南",
            value: "济南"
        }, {
            name: "嘉兴",
            value: "嘉兴"
        }, {
            name: "昆明",
            value: "昆明"
        }, {
            name: "宁波",
            value: "宁波"
        }, {
            name: "南昌",
            value: "南昌"
        }, {
            name: "南京",
            value: "南京"
        }, {
            name: "青岛",
            value: "青岛"
        }, {
            name: "泉州",
            value: "泉州"
        }, {
            name: "沈阳",
            value: "沈阳"
        }, {
            name: "苏州",
            value: "苏州"
        }, {
            name: "天津",
            value: "天津"
        }, {
            name: "温州",
            value: "温州"
        }, {
            name: "无锡",
            value: "无锡"
        }, {
            name: "武汉",
            value: "武汉"
        }, {
            name: "西安",
            value: "西安"
        }, {
            name: "厦门",
            value: "厦门"
        }, {
            name: "郑州",
            value: "郑州"
        }, {
            name: "中山",
            value: "中山"
        }, {
            name: "石家庄",
            value: "石家庄"
        }, {
            name: "哈尔滨",
            value: "哈尔滨"
        }, {
            name: "安徽",
            value: "安徽"
        }, {
            name: "福建",
            value: "福建"
        }, {
            name: "甘肃",
            value: "甘肃"
        }, {
            name: "广东",
            value: "广东"
        }, {
            name: "广西",
            value: "广西"
        }, {
            name: "贵州",
            value: "贵州"
        }, {
            name: "海南",
            value: "海南"
        }, {
            name: "河北",
            value: "河北"
        }, {
            name: "河南",
            value: "河南"
        }, {
            name: "湖北",
            value: "湖北"
        }, {
            name: "湖南",
            value: "湖南"
        }, {
            name: "江苏",
            value: "江苏"
        }, {
            name: "江西",
            value: "江西"
        }, {
            name: "吉林",
            value: "吉林"
        }, {
            name: "辽宁",
            value: "辽宁"
        }, {
            name: "宁夏",
            value: "宁夏"
        }, {
            name: "青岛",
            value: "青岛"
        }, {
            name: "山东",
            value: "山东"
        }, {
            name: "山西",
            value: "山西"
        }, {
            name: "陕西",
            value: "陕西"
        }, {
            name: "云南",
            value: "云南"
        }, {
            name: "四川",
            value: "四川"
        }, {
            name: "西藏",
            value: "西藏"
        }, {
            name: "新疆",
            value: "新疆"
        }, {
            name: "浙江",
            value: "浙江"
        }, {
            name: "澳门",
            value: "澳门"
        }, {
            name: "香港",
            value: "香港"
        }, {
            name: "台湾",
            value: "台湾"
        }, {
            name: "内蒙古",
            value: "内蒙古"
        }, {
            name: "黑龙江",
            value: "黑龙江"
        }
    ];

    return {
        CONDITION_MAP: conditionMap,
        LOCS_LIST:locsList
    }
});